### PR TITLE
Fix support for separating lines

### LINKED ISSUE #246: Adding a SEPARATING_LINE fails, for any format with padding
If a format with padding is used, the test for SEPARATING_LINE fails, resulting in a table containing an (unprintable) \x01 character instead of a separating line.

This is because the padding is applied before the test for SEPARATING_LINE.  The row now contains " \x01 ", instead of "\x01", so the test fails.

However, since multi-line cells are post-padded, the test succeeds, and a separating line is added!

So, instead of pre-padding the rows, always pad them immediately before output.

### PR DESCRIPTION
**Pull request by pjkundert**
Resolves #246

### CODE REVIEW

**Comment by davidlatte** [comment]
It would be great to get this PR merged and released!

**Comment by astanin** [comment]
I tried merging this commit with master (see pr-279 branch), but the tests fail in test_simple_headerless_with_sep_line_with_linebetweenrows_in_tablefmt.

Expected output:

```
+------+----------+
| spam |  41.9999 |
+------+----------+
+------+----------+
| eggs | 451      |
+------+----------+
```

actual output:

```
+------+----------+
| spam |  41.9999 |
+------+----------+
||
+------+----------+
| eggs | 451      |
+------+----------+
```

Possible interaction with the changes introduced in pull request #331

**Comment by pjkundert** [comment]
A check for SEPARATING_LINE got skipped, @astatin; I added it back in.  Passes tests now.

**Comment by astanin** [comment]
@pjkundert Thank you. I think this can be merged now.

**Comment by ciriousjoker** [comment]
So when is this going to get released? v0.9.0 is still the most up to date version and it's from 2022 or am I missing something?

**Pull request merged**
