### PR TITLE
preserve_whitespace as an argument to tabulate()

### LINKED ISSUE #37: PRESERVE_WHITESPACE should be made an argument
It's currently a module-level global variable. This is assuming that all users of tabulate uses the same PRESERVE_WHITESPACE setting. This will not work well if different use of tabulate needs different settings.

Having an argument for this setting would be more general.

### PR DESCRIPTION
**Pull request by vrza**
Replace constant `PRESERVE_WHITESPACE` with optional argument `preserve_whitespace=False`

Resolves #37.

### CODE REVIEW

**Comment by astanin** [comment]
This is a breaking change, so it will be postponed at least until the next major release.

What is the reason to remove PRESERVE_WHITESPACE macro? I'm pretty sure some users rely on it.

**Comment by vrza** [comment]
The reasons are cleanliness of design and clear user facing API, with no [monkey patching](https://en.wikipedia.org/wiki/Monkey_patch) necessary.

To explain in detail, `PRESERVE_WHITESPACE` is not a macro, but rather a constant defined as a property of the `tabulate` module. In order to change the whitespace behavior this constant affects, the consumer must monkey patch the tabulate module. You can see an example of this in [this unit test](https://github.com/astanin/python-tabulate/blob/bfc922cb04aa4a8bfe6360a50ac774d513605043/test/test_output.py#L1601).

Monkey patching alters the default module state and this can lead to problems. For example, if one user function monkey patches the module at runtime, and doesn't patch it back to its original state after use, a second user function, called subsequently, that's relying on the default behavior, might fail or produce unexpected results.

You can see this in action by splitting the `test_preserve_whitespace` unit test into two tests (and it really does contain two distinct tests, hiding inside one function):

```
def test_preserve_whitespace_true():
    "Output: Default table output, but with preserved leading whitespace."
    tabulate_module.PRESERVE_WHITESPACE = True
    table_headers = ["h1", "h2", "h3"]
    test_table = [["  foo", " bar   ", "foo"]]
    expected = "\n".join(
        ["h1     h2       h3", "-----  -------  ----", "  foo   bar     foo"]
    )
    result = tabulate(test_table, table_headers)
    assert_equal(expected, result)

def test_preserve_whitespace_default():
    table_headers = ["h1", "h2", "h3"]
    test_table = [["  foo", " bar   ", "foo"]]
    expected = "\n".join(["h1    h2    h3", "----  ----  ----", "foo   bar   foo"])
    result = tabulate(test_table, table_headers)
    assert_equal(expected, result)
```
    
If `test_preserve_whitespace_default` runs first, and `test_preserve_whitespace_true` second, both tests will pass. However, if the `test_preserve_whitespace_true` runs first, then `test_preserve_whitespace_default` will fail, because the first test monkey patches the tabulate module and doesn't patch it back after use.

You can read about more monkey patching pitfalls in [the wikipedia article.](https://en.wikipedia.org/wiki/Monkey_patch). For these reasons, it's not a good idea to make monkey patching a standard way of using the library. This is why I moved the `preserve_whitespace` tunable to the constructor, as an optional argument with a default value, resulting in a cleaner API which is less error-prone to use. The functionality is still there, it is just exposed to the user in a more user-friendly style.

Indeed, this change will break user programs that rely on monkey patching the `tabulate.PRESERVE_WHITESPACE` property, and as such, according to semantic versioning guidelines, seems to warrant a major version bump.

**Comment by astanin** [comment]
Related: #37

**Comment by astanin** [comment]
I generally agree with you. I'm going to integrate your changes in the 0.9 release, whenever it can be.

**Comment by vrza** [comment]
Sounds good. Rebased this feature branch to latest upstream master just now.

**Comment by astanin** [comment]
Merged changed to pr-79 branch.

**Pull request merged**
